# Copy this file to your repo at: .github/workflows/agentic-developer.yml
# Replace OWNER/bc-agentic-workflow with your org's repo path.

name: Agentic Developer

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: "Issue number to implement"
        type: string
        required: true
      review_cycle:
        description: "Current review cycle"
        type: string
        required: true
        default: "0"
      max_review_cycles:
        description: "Max review cycles"
        type: string
        required: false
        default: "3"
      project_node_id:
        description: "Project node ID"
        type: string
        required: false
        default: ""
      item_node_id:
        description: "Project item node ID"
        type: string
        required: false
        default: ""

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: write

jobs:
  develop:
    uses: OWNER/bc-agentic-workflow/.github/workflows/developer.yml@main
    with:
      issue_number: ${{ inputs.issue_number }}
      review_cycle: ${{ inputs.review_cycle }}
      max_review_cycles: ${{ inputs.max_review_cycles }}
      project_node_id: ${{ inputs.project_node_id }}
      item_node_id: ${{ inputs.item_node_id }}
    secrets: inherit
