# This file goes in your org's .github repository at:
# .github/workflows/orchestrator-trigger.yml
#
# It triggers when the Cloudflare Worker webhook relay forwards
# projects_v2_item events as repository_dispatch.
# Replace OWNER/bc-agentic-workflow with your org's actual path.

name: Orchestrator Trigger

on:
  repository_dispatch:
    types: [projects_v2_item]

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: write

jobs:
  orchestrate:
    # Only trigger for issues when a single-select field (e.g. Status) changes
    if: >-
      github.event.client_payload.projects_v2_item.content_type == 'Issue' &&
      github.event.client_payload.changes.field_value.field_type == 'single_select'
    uses: OWNER/bc-agentic-workflow/.github/workflows/orchestrator.yml@main
    with:
      item_node_id: ${{ github.event.client_payload.projects_v2_item.node_id }}
      content_node_id: ${{ github.event.client_payload.projects_v2_item.content_node_id }}
      project_node_id: ${{ github.event.client_payload.projects_v2_item.project_node_id }}
    secrets: inherit
