# This file goes in your org's .github repository at:
# .github/workflows/orchestrator-trigger.yml
#
# It triggers when items on an org-level GitHub Project change status.
# Replace OWNER/bc-agentic-workflow with your org's actual path.

name: Orchestrator Trigger

on:
  projects_v2_item:
    types: [edited]

jobs:
  orchestrate:
    # Only run for issue items (not PRs or draft issues)
    if: github.event.projects_v2_item.content_type == 'Issue'
    uses: OWNER/bc-agentic-workflow/.github/workflows/orchestrator.yml@main
    with:
      item_node_id: ${{ github.event.projects_v2_item.node_id }}
      content_node_id: ${{ github.event.projects_v2_item.content_node_id }}
      project_node_id: ${{ github.event.projects_v2_item.project_node_id }}
    secrets: inherit
